# Generated by Django 5.1.3 on 2024-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0002_rename_campregistrationtable_camptable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fooddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('dicscription', models.CharField(blank=True, max_length=100, null=True)),
                ('food_status', models.CharField(blank=True, max_length=100, null=True)),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
