# Generated by Django 5.1.3 on 2024-12-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0004_remove_fooddetails_dicscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
