# Generated by Django 5.1.3 on 2024-12-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0005_alter_notificationtable_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageTable',
        ),
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='Name',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='LOGINID',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='Quantity',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='Status',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='User',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='complainttable',
            name='LOGINID',
        ),
        migrations.RemoveField(
            model_name='complainttable',
            name='Submit',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Review',
        ),
        migrations.RemoveField(
            model_name='informationtable',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='Date',
        ),
        migrations.AddField(
            model_name='complainttable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complainttable',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.usertable'),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='RESTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.resturanttable'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationtable',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationtable',
            name='Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
