# Generated by Django 5.1.3 on 2024-12-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0006_delete_managetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.logintable'),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.logintable'),
        ),
        migrations.AlterField(
            model_name='informationtable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
