# Generated by Django 5.1.3 on 2024-12-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0007_feedbacktable_date_itemtable_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='Rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
