# Generated by Django 5.1.3 on 2024-12-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0008_feedbacktable_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainttable',
            name='USER',
        ),
        migrations.AddField(
            model_name='complainttable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.logintable'),
        ),
    ]
