# Generated by Django 5.1.3 on 2024-12-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0009_remove_complainttable_user_complainttable_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
