# Generated by Django 5.1.3 on 2024-12-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0010_alter_requesttable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='camptable',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
