# Generated by Django 5.1.3 on 2024-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0011_camptable_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingstatusTable',
        ),
        migrations.AddField(
            model_name='camptable',
            name='Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
