# Generated by Django 5.1.3 on 2025-02-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0012_delete_workingstatustable_camptable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.itemtable'),
        ),
    ]
