# Generated by Django 5.1.3 on 2025-02-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0013_alter_requesttable_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationtable',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='donationtable',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='donationtable',
            name='Submit',
        ),
        migrations.AddField(
            model_name='donationtable',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationtable',
            name='Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='godnesshub_app.logintable'),
        ),
    ]
