# Generated by Django 5.1.3 on 2025-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0014_remove_donationtable_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttable',
            old_name='Request',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='requesttable',
            name='Quantity',
        ),
    ]
