# Generated by Django 5.1.3 on 2025-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0015_rename_request_requesttable_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
