# Generated by Django 5.1.3 on 2025-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0016_itemtable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
