# Generated by Django 5.1.3 on 2025-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godnesshub_app', '0017_requesttable_category_requesttable_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='Item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
